services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.interfaces.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
