[tool.black]
line-length = 100
target-version = ['py312']
skip-string-normalization = true

[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = true

[tool.mypy]
strict = false
warn_unused_configs = false
ignore_missing_imports = true
disable_error_code = "import-untyped"

[tool.pydocstyle]
ignore = ["D100", "D104", "D202", "D203", "D212", "D406", "D407", "D413", "D415"]
match-dir = "[^\\.].*"
